### ISSUE TITLE
filtertools.decompose doesn't work when product of spatial dimensions < 42

### ISSUE THREAD

**Issue by lmcintosh** [baccuslab/pyret#62] opened 2015-11-05 18:31 UTC
To reproduce bug, try 

sta = np.random.randn(6,6,40)
spatial_rf, temporal_rf = ft.decompose(sta)

The if the first two spatial dimensions of the STA are (6,7), (7,6), (7,7), (8,8), etc. it always, works, but for whenever you have spatial dimensions of (6,6) or smaller, filtertools.decompose improperly concatenates the two spatial dimensions. This results in the error "ValueError: operands could not be broadcast together with shapes (36,40) (36,)" for the case when the STA is of size (6,6,40), or "ValueError: operands could not be broadcast together with shapes (16,40) (16,)" when the STA is of size (4,4,40).

**Comment by nirum** [comment] 2015-11-05 18:53
which branch are you using?

**Comment by nirum** [comment] 2015-11-05 18:57
The `dev` branch uses flipped dimensions now, so the temporal axis is first (see https://github.com/baccuslab/pyret/pull/58 for discussion on why we did this).

Therefore (in `dev`) you want to pass something with the shape of (40,6,6) to `ft.decompose` :whale:

**Comment by lmcintosh** [comment] 2015-11-05 19:50
Yeah I tested it on the master branch. I can see if I get a similar error
on dev branch.


--
Lane McIntosh
www.lanemcintosh.com

**Comment by nirum** [comment] 2015-11-05 19:59
ya I can reproduce the bug on `master`

**Comment by lmcintosh** [comment] 2015-11-05 20:17
works in dev!

**Comment by nirum** [comment] 2015-11-05 22:30
re-opening because it needs to get fixed in master

**Closed** 2015-12-12 02:47 UTC
Labels: bug
